---
- name: Configure Workspace
  hosts: localhost
  tasks:
    - name: Configure my user
      user:
        name: gsaxby
        comment: "Gareth Saxby"
        create_home: yes
        groups:
          - adm
          - cdrom
          - sudo
          - dip
          - plugdev
          - lxd
        append: yes
        shell: /usr/bin/zsh
        state: present
      become: yes

    - name: Add Desired Repository Keys
      apt_key:
        url: "{{ item }}"
        state: present
      become: yes
      loop:
        - https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add Desired Repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      become: yes
      loop:
        - deb https://apt.kubernetes.io/ kubernetes-xenial main

    - name: Install Packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        force_apt_get: yes
      become: yes
      vars:
        packages:
          - git
          - kubectl
          - virtualenv
          - python-setuptools
          - python3-setuptools
          - unzip
          - jq
          - neovim
          - gnupg-utils
          - zsh
          - binutils
          - bison
          - gcc
          - make
          - golang

    - name: Install Python Packages
      pip:
        name: "{{ packages }}"
        virtualenv: /home/gsaxby/.python_env/
        virtualenv_python: python3.8
        state: latest
      vars:
        packages:
        - pre-commit
        - awscli
        - ansible
        - ansible-lint

    - name: Create User bin Directory
      file:
        dest: /home/gsaxby/bin/
        state: directory

    - name: Link Python Applications
      file:
        dest: "/home/gsaxby/bin/{{ item }}"
        src: "/home/gsaxby/.python_env/bin/{{ item }}"
        state: link
      loop:
      - pre-commit
      - pre-commit-validate-manifest
      - pre-commit-validate-config
      - aws
      - ansible
      - ansible-playbook
      - ansible-config
      - ansible-connection
      - ansible-console
      - ansible-doc
      - ansible-galaxy
      - ansible-inventory
      - ansible-pull
      - ansible-vault
      - ansible-lint

    - name: Download HashiCorp Tools
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.filename }}"
        checksum: "{{ item.checksum }}"
      loop:
      - { url: "https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip", filename: "terraform.zip", checksum: "sha256:be99da1439a60942b8d23f63eba1ea05ff42160744116e84f46fc24f1a8011b6" }
      - { url: "https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip", filename: "packer.zip", checksum: "sha256:2abb95dc3a5fcfb9bf10ced8e0dd51d2a9e6582a1de1cab8ccec650101c1f9df" }
      - { url: "https://releases.hashicorp.com/vault/1.4.2/vault_1.4.2_linux_amd64.zip", filename: "vault.zip", checksum: "sha256:f2bca89cbffb8710265eb03bc9452cc316b03338c411ba8453ffe7419390b8f1" }
      - { url: "https://releases.hashicorp.com/consul/1.7.3/consul_1.7.3_linux_amd64.zip", filename: "consul.zip", checksum: "sha256:453814aa5d0c2bc1f8843b7985f2a101976433db3e6c0c81782a3c21dd3f9ac3" }
      - { url: "https://releases.hashicorp.com/nomad/0.11.2/nomad_0.11.2_linux_amd64.zip", filename: "nomad.zip", checksum: "sha256:0c190d3cca12b75645e946e49207bf62bff8e0d8f52eee43dc059dbb8814da99" }

    - name: Extract HashiCorp Tools
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /home/gsaxby/bin/
      loop:
      - terraform.zip
      - packer.zip
      - vault.zip
      - consul.zip
      - nomad.zip

    - name: Download Helm
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.filename }}"
        checksum: "{{ item.checksum }}"
      loop:
      - { url: "https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz", filename: "helm.tar.gz", checksum: "sha256:018f9908cb950701a5d59e757653a790c66d8eda288625dbb185354ca6f41f6b" }
    
    - name: Extract Helm
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /tmp/
      loop:
      - helm.tar.gz

    - name: Move Helm into location
      copy:
        src: /tmp/linux-amd64/helm
        dest: /home/gsaxby/bin/
        owner: gsaxby
        group: gsaxby
        mode: '0700'

    - name: Set Default Editor
      alternatives:
        name: "{{ item }}"
        path: /usr/bin/nvim
      become: yes
      loop:
      - vi
      - vim
      - editor

    - name: Set git Configuration
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
        state: present
      loop:
      - { name: "user.email", value: "garethsaxby@users.noreply.github.com" }
      - { name: "user.name", value: "Gareth Saxby" }
      - { name: "core.editor", value: "vim" }
      - { name: "push.default", value: "current" }