---
- name: Configure Workspace
  hosts: localhost
  tasks:
    - name: Brew Taps
      community.general.homebrew_tap:
        name:
          - instrumenta/instrumenta
          - chef/chef
          - homebrew/cask-fonts
          - hashicorp/tap
        state: present

    - name: Upgrade Homebrew
      community.general.homebrew:
        update_homebrew: yes

    - name: Install Brew Packages
      community.general.homebrew:
        state: present
        name:
          - act
          - ansible
          - ansible-lint
          - argocd
          - atlantis
          - aspell
          - awscli
          - aws-cdk
          - aws-keychain
          - bash
          - bazel
          - bfg
          - binutils
          - hashicorp/tap/boundary
          - cfn-lint
          - cfssl
          - checkbashisms
          - clair
          - cloudformation-cli
          - cloud-nuke
          - conftest
          - hashicorp/tap/consul
          - curl
          - diffutils
          - doctl
          - dos2unix
          - eksctl
          - exercism
          - findutils
          - flyway
          - gawk
          - gh
          - git
          - gnu-getopt
          - gnu-indent
          - gnu-sed
          - gnu-tar
          - go
          # - goenv - Does not install the latest version - See https://github.com/syndbg/goenv/issues/123
          - hadolint
          - helm
          - httpie
          - hugo
          - iftop
          - istioctl
          - kops
          - kubernetes-cli
          - jq
          - linkerd
          - mas
          - minikube
          - mosh
          - mpv
          - mtr
          - neovim
          - nmap
          - hashicorp/tap/nomad
          - openssh
          - openssl
          - buildpacks/tap/pack
          - hashicorp/tap/packer
          - pre-commit
          - prettyping
          - prometheus
          - pulumi
          - pwgen
          - pyenv
          - pyenv-virtualenv
          - readline
          - ruby
          - sceptre
          - sops
          - shellcheck
          - sqlite
          - sqlite3
          - svn
          - task
          - telnet
          - hashicorp/tap/terraform
          - terraform-docs
          - terragrunt
          - tflint
          - hashicorp/tap/vault
          - watch
          - hashicorp/tap/waypoint
          - wget
          - xz
          - youtube-dl
          - zlib
          - zsh

    - name: Install Brew Cask Packages
      homebrew_cask:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - alfred
          - aerial
          - balenaetcher
          - bartender
          - caffeine
          - cyberduck
          - dash
          - docker
          - dropbox
          - firefox
          - flux
          - fly
          - font-fira-code
          - font-source-code-pro-for-powerline
          - goland
          - google-chrome
          - google-cloud-sdk
          - inspec
          - intel-power-gadget
          - istat-menus
          - iterm2
          - micro-snitch
          - muzzle
          - nordvpn
          - nova
          - opera
          - racket
          - sentinel
          - session-manager-plugin
          - shiftit
          - slack
          - spotify
          - sublime-text
          - the-unarchiver
          - vagrant
          - virtualbox
          - viscosity
          - visual-studio-code
          - vlc
          - zoomus

    - name: Install App Store Packages
      community.general.mas:
        id:
          - 585829637 # Todoist
          - 975937182 # Fantastical
          - 1091189122 # Bear
          - 1295203466 # Microsoft Remote Desktop

    - name: Create Setup Folder
      file:
        path: /Users/gsaxby/setup/
        owner: gsaxby
        group: staff
        mode: 0755
        state: directory

    - name: Clone DotFiles Repo
      git:
        repo: https://github.com/garethsaxby/dotfiles.git
        dest: /Users/gsaxby/setup/dotfiles/
