---
- name: Configure Workspace
  hosts: localhost
  tasks:
    - name: Configure my user
      user:
        name: gsaxby
        comment: "Gareth Saxby"
        create_home: yes
        groups:
          - adm
          - cdrom
          - sudo
          - dip
          - plugdev
          - lxd
        append: yes
        shell: /usr/bin/zsh
        state: present
      become: yes

    - name: Add Desired Repository Keys
      apt_key:
        url: "{{ item }}"
        state: present
      become: yes
      loop:
        - https://packages.cloud.google.com/apt/doc/apt-key.gpg
        - https://download.docker.com/linux/ubuntu/gpg
        - https://apt.releases.hashicorp.com/gpg

    - name: Add Desired Repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      become: yes
      loop:
        - deb https://apt.kubernetes.io/ kubernetes-xenial main
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        - deb [arch=amd64] https://apt.releases.hashicorp.com focal main

    - name: Install Packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        force_apt_get: yes
      become: yes
      vars:
        packages:
          - nmap
          - dos2unix
          - git
          - kubectl
          - virtualenv
          - python-setuptools
          - python3-setuptools
          - unzip
          - jq
          - neovim
          - gnupg-utils
          - zsh
          - binutils
          - bison
          - gcc
          - make
          - golang
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - shellcheck
          - vault
          - consul
          - nomad

    - name: Install Python Packages
      pip:
        name: "{{ packages }}"
        virtualenv: /home/gsaxby/.python_env/
        virtualenv_python: python3.8
        state: latest
      vars:
        packages:
        - pre-commit
        - awscli
        - ansible
        - ansible-lint
        - sceptre
        - terraform-compliance

    - name: Create User bin Directory
      file:
        dest: /home/gsaxby/bin/
        state: directory

    - name: Link Python Applications
      file:
        dest: "/home/gsaxby/bin/{{ item }}"
        src: "/home/gsaxby/.python_env/bin/{{ item }}"
        state: link
      loop:
      - pre-commit
      - pre-commit-validate-manifest
      - pre-commit-validate-config
      - aws
      - ansible
      - ansible-playbook
      - ansible-config
      - ansible-connection
      - ansible-console
      - ansible-doc
      - ansible-galaxy
      - ansible-inventory
      - ansible-pull
      - ansible-vault
      - ansible-lint
      - sceptre
      - terraform-compliance

    - name: Download HashiCorp Tools
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.filename }}"
        checksum: "{{ item.checksum }}"
      loop:
      - {
          url: "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip",
          filename: "terraform.zip",
          checksum: "sha256:872245d9c6302b24dc0d98a1e010aef1e4ef60865a2d1f60102c8ad03e9d5a1d"
        }
      - {
          url: "https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip",
          filename: "packer.zip",
          checksum: "sha256:a678c995cb8dc232db3353881723793da5acc15857a807d96c52e96e671309d9"
        }
      - {
          url: "https://releases.hashicorp.com/sentinel/0.15.6/sentinel_0.15.6_linux_amd64.zip",
          filename: "sentinel.zip",
          checksum: "sha256:83b607b3c86836362dcbd55dc65a497a4ee6056a72ba63f35a01e145e3076198"
        }

    - name: Extract HashiCorp Tools
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /home/gsaxby/bin/
      loop:
      - terraform.zip
      - packer.zip
      - sentinel.zip

    - name: Download tflint
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.filename }}"
        checksum: "{{ item.checksum }}"
      loop:
      - {
          url: "https://github.com/terraform-linters/tflint/releases/download/v0.18.0/tflint_linux_amd64.zip",
          filename: "tflint.zip",
          checksum: "sha256:9e6c536577e4969b59fa2e219a45ae62a324dfaacfe2fde796d35de2092087f8"
        }

    - name: Extract tflint
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /home/gsaxby/bin/
      loop:
      - tflint.zip

    - name: Install terraform-docs
      get_url:
        url: "https://github.com/terraform-docs/terraform-docs/releases/download/v0.9.1/terraform-docs-v0.9.1-linux-amd64"
        dest: "/home/gsaxby/bin/terraform-docs"
        checksum: "sha256:ceb4e7f291d43a5f7672f7ca9543075554bacd02cf850e6402e74f18fbf28f7e"
        mode: 0700
        owner: "gsaxby"
        group: "gsaxby"

    - name: Install tfsec
      get_url:
        url: "https://github.com/liamg/tfsec/releases/download/v0.24.1/tfsec-linux-amd64"
        dest: "/home/gsaxby/bin/tfsec"
        checksum: "sha256:e4325e5eaf5025d772f65b96d424cd3b3855176bbb483efda20f02fd416a6921"
        mode: 0700
        owner: "gsaxby"
        group: "gsaxby"

    - name: Install terragrunt
      get_url:
        url: "https://github.com/gruntwork-io/terragrunt/releases/download/v0.23.31/terragrunt_linux_amd64"
        dest: "/home/gsaxby/bin/terragrunt"
        checksum: "sha256:efd124c2b9f406c0eb81b646e6b9eb32056095b38a130e6dc9a27d4be9bc25d9"
        mode: 0700
        owner: "gsaxby"
        group: "gsaxby"

    - name: Download Helm
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.filename }}"
        checksum: "{{ item.checksum }}"
      loop:
      - {
          url: "https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz",
          filename: "helm.tar.gz",
          checksum: "sha256:8eb56cbb7d0da6b73cd8884c6607982d0be8087027b8ded01d6b2759a72e34b1"
        }

    - name: Extract Helm
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /tmp/
      loop:
      - helm.tar.gz

    - name: Move Helm into location
      copy:
        src: /tmp/linux-amd64/helm
        dest: /home/gsaxby/bin/
        owner: gsaxby
        group: gsaxby
        mode: '0700'

    - name: Download Inspec
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.filename }}"
        checksum: "{{ item.checksum }}"
      loop:
      - {
          url: "https://packages.chef.io/files/stable/inspec/4.22.1/ubuntu/20.04/inspec_4.22.1-1_amd64.deb",
          filename: "inspec.deb",
          checksum: "sha256:6ef7db78a41c5ba5f2b0ddc10c915dc70e1a3634ca41105f8c40b745960256be"
      }

    - name: Install Inspec
      apt:
        deb: "/tmp/inspec.deb"
        state: present
      become: yes

    - name: Set Default Editor
      alternatives:
        name: "{{ item }}"
        path: /usr/bin/nvim
      become: yes
      loop:
      - vi
      - vim
      - editor

    - name: Set git Configuration
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
        state: present
      loop:
      - { name: "user.email", value: "garethsaxby@users.noreply.github.com" }
      - { name: "user.name", value: "Gareth Saxby" }
      - { name: "core.editor", value: "vim" }
      - { name: "push.default", value: "current" }